import type { ProviderCatalogEntry } from "@/lib/integrations/types";

export const INTEGRATION_PROVIDERS: ProviderCatalogEntry[] = [
  {
    id: "hubspot",
    displayName: "HubSpot",
    description: "Sync contacts to HubSpot CRM",
    category: "crm",
    authType: "oauth2",
    supportsOAuth: true,
    supportsApiKey: true,
    supportsWebhooks: false,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: ["crm.objects.contacts.read", "crm.objects.contacts.write"],
    docsUrl: "https://developers.hubspot.com/docs/api/overview",
  },
  {
    id: "gohighlevel",
    displayName: "GoHighLevel",
    description: "Sync contacts to GoHighLevel CRM",
    category: "crm",
    authType: "api_key",
    supportsOAuth: false,
    supportsApiKey: true,
    supportsWebhooks: false,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: [],
    docsUrl: "https://highlevel.stoplight.io/docs/integrations/",
  },
  {
    id: "n8n",
    displayName: "n8n",
    description: "Workflow automation webhook endpoint",
    category: "automation",
    authType: "webhook",
    supportsOAuth: false,
    supportsApiKey: true,
    supportsWebhooks: true,
    supportsInbound: true,
    supportsOutbound: true,
    requiredScopes: [],
    docsUrl: "https://docs.n8n.io/",
  },
  {
    id: "slack",
    displayName: "Slack",
    description: "Receive notifications in Slack channels",
    category: "communication",
    authType: "oauth2",
    supportsOAuth: true,
    supportsApiKey: false,
    supportsWebhooks: true,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: ["incoming-webhook"],
    docsUrl: "https://api.slack.com/docs",
  },
  {
    id: "tally",
    displayName: "Tally",
    description: "Capture leads from Tally forms",
    category: "lead-capture",
    authType: "webhook",
    supportsOAuth: false,
    supportsApiKey: false,
    supportsWebhooks: true,
    supportsInbound: true,
    supportsOutbound: false,
    requiredScopes: [],
    docsUrl: "https://tally.so/help/webhooks",
  },
  {
    id: "twilio",
    displayName: "Twilio",
    description: "Read-only account and source-number validation",
    category: "communication",
    authType: "api_key",
    supportsOAuth: false,
    supportsApiKey: true,
    supportsWebhooks: false,
    supportsInbound: false,
    supportsOutbound: false,
    requiredScopes: [],
    docsUrl: "https://www.twilio.com/docs",
  },
  {
    id: "google-calendar",
    displayName: "Google Calendar",
    description: "Schedule and manage appointments",
    category: "google-workspace",
    authType: "oauth2",
    supportsOAuth: true,
    supportsApiKey: false,
    supportsWebhooks: false,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: ["https://www.googleapis.com/auth/calendar"],
    docsUrl: "https://developers.google.com/calendar/api",
  },
  {
    id: "gmail",
    displayName: "Gmail",
    description: "Send and track emails via Google Workspace",
    category: "google-workspace",
    authType: "oauth2",
    supportsOAuth: true,
    supportsApiKey: false,
    supportsWebhooks: false,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
    docsUrl: "https://developers.google.com/gmail/api",
  },
  {
    id: "zapier",
    displayName: "Zapier",
    description: "Connect Revora to 7000+ apps via Zapier",
    category: "automation",
    authType: "webhook",
    supportsOAuth: false,
    supportsApiKey: false,
    supportsWebhooks: true,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: [],
    docsUrl: "https://platform.zapier.com/",
  },
  {
    id: "make",
    displayName: "Make",
    description: "Visual automation and integration builder",
    category: "automation",
    authType: "webhook",
    supportsOAuth: false,
    supportsApiKey: false,
    supportsWebhooks: true,
    supportsInbound: false,
    supportsOutbound: true,
    requiredScopes: [],
    docsUrl: "https://www.make.com/en/help",
  },
];

export function getProviderById(id: string): ProviderCatalogEntry | undefined {
  return INTEGRATION_PROVIDERS.find((p) => p.id === id);
}

export function getProvidersByCategory(
  category: string,
): ProviderCatalogEntry[] {
  return INTEGRATION_PROVIDERS.filter((p) => p.category === category);
}

export const PROVIDER_CATEGORIES = [
  { key: "crm", label: "CRM" },
  { key: "automation", label: "Automation" },
  { key: "communication", label: "Communication" },
  { key: "lead-capture", label: "Lead Capture" },
  { key: "google-workspace", label: "Google Workspace" },
] as const;
