-- ============================================================================
-- AI Growth - Owner protection cascade correction
-- Phase 14.4D.1B
--
-- Preserve the owner invariant while an organization exists, but allow the
-- membership delete generated by the organization's ON DELETE CASCADE.
-- ============================================================================

begin;

create or replace function public.protect_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' and old.role = 'owner' then
    -- A direct membership delete (including an auth/profile cascade) must not
    -- orphan a live organization. During organizations.id ON DELETE CASCADE,
    -- the parent organization row is already gone, so this is the narrow
    -- legitimate path that may remove an owner membership.
    if exists (
      select 1
      from public.organizations as organization_row
      where organization_row.id = old.organization_id
    ) then
      raise exception
        'Owner memberships cannot be deleted while their organization exists';
    end if;

    return old;
  end if;

  if tg_op = 'UPDATE' and old.role = 'owner' and (
    new.profile_id is distinct from old.profile_id
    or new.organization_id is distinct from old.organization_id
    or new.role is distinct from 'owner'
    or new.status is distinct from 'active'
  ) then
    raise exception
      'Owner memberships require the dedicated ownership transfer workflow';
  end if;

  return new;
end;
$$;

-- Trigger functions are internal-only. Reassert the existing least-privilege
-- posture after replacing the function definition.
revoke execute on function public.protect_owner_membership()
  from public, anon, authenticated;

commit;
